# This docker-compose file is configured to run Synqly Embedded locally for 
# test purposes. Synqly Embedded combines Synqly's Management and Connector APIs
# documented here: https://docs.synqly.com/reference/api-overview
#
# Synqly APIs will be available at localhost:9000
volumes:
  embedded-database:
  embedded-mail:

services:
  embedded:
    image: quay.io/synqly/embedded:latest
    # (Demo) Update the following values:
    #   --organization-name: Name of the generated Synqly Organization
    #   (if running embedded-mail): 
    #   --invite-member: email address to invite as the default admin of the generated Synqly Organization
    #
    # (Production) Update the following values:
    #  --organization-name: Name of the generated Synqly Organization
    #  --db-host: Hostname of a production-ready Postgres compatible DB
    #  --db-user: DB username
    #  --db-pass: DB Password
    command: >
      embedded --organization-name=${SYNQLY_ORG_NAME} --organization-fullname=${SYNQLY_ORG_FULL_NAME} \
        --level=-1 --requests-per-min=10000 --db-host=embedded-database \
        --db-port=5432 --db-user ${DB_USER} --db-pass ${DB_PASS} \
        --port=9040 --token=${SYNQLY_ROOT_TOKEN} --token-signing-key=${SYNQLY_TOKEN_SIGNING_KEY} \
        --smtp-server=embedded-mail:1025 --smtp-user=${SMTP_USER} \
        --smtp-pass=${SMTP_PASS}  --smtp-tls=false --smtp-domain=http://localhost:3000 \
        --invite-member="test@sample.com"
    ports:
      - "9000:9040"
    depends_on:
      embedded-database:
        condition: service_healthy
        restart: true
        
  # (Demo only) Runs a single-node PostgreSQL instance locally. This is not
  # supported for production. If running in a production environment, use a
  # durable externally managed database instead.
  embedded-database:
    image: postgres:16.4
    ports:
      - 5432:5432
    volumes:
      - ~/demo-apps/embedded-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=synqly
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U demo_synqly -d synqly']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  # (Optional, Demo Only) Runs a local SMTP server for testing email functionality. 
  # If enabled, set --smtp-server, --smtp-user, --smtp-pass, --smtp-domain, and 
  # --smtp-tls on the embedded service. 
  embedded-mail:
    image: axllent/mailpit
    restart: always
    volumes:
      - embedded-mail:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: nc -z localhost 8025
      interval: 3s
      timeout: 3s
      retries: 10
